export const products = [
  { id:'croissant', name:'Butter croissant', category:'Viennoiserie', description:'Golden, flaky, wonderfully buttery.', price:380, image:'https://images.unsplash.com/photo-1623334044303-241021148842?fm=jpg&q=80&w=1080&fit=max', badge:'BAKERY FAVORITE', detail:'A classic French butter croissant, baked at Maison Odile.', whole:false },
  { id:'chocolate', name:'Choc-Odile', category:'Viennoiserie', description:'Our take on pain au chocolat.', price:440, image:'https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?fm=jpg&q=80&w=1080&fit=max', badge:'CHOCOLATE LOVE', detail:'Buttery pastry with a chocolate center.', whole:false },
  { id:'macaron', name:'French macarons', category:'Pâtisserie', description:'A colorful little moment of joy.', price:270, image:'https://images.unsplash.com/photo-1569864358642-9d1684040f43?fm=jpg&q=80&w=1080&fit=max', badge:'PETIT & PERFECT', detail:'Priced per macaron. The bakery confirms available flavors.', whole:false },
  { id:'flan', name:'Flan parisien', category:'Cakes & tarts', description:'A whole French vanilla custard pie.', price:4200, image:'https://images.unsplash.com/photo-1591107576521-87091dc07797?fm=jpg&q=80&w=1080&fit=max', badge:'FOR SHARING', detail:'Whole flan, without a chocolate sign. Optional decorations can be requested through the bakery’s official menu.', whole:true },
  { id:'tarte', name:'Tarte citron', category:'Cakes & tarts', description:'A bright, beautiful lemon tart.', price:4400, image:'https://images.unsplash.com/photo-1543508185-225c92847541?fm=jpg&q=80&w=1080&fit=max', badge:'48-HOUR PREORDER', detail:'The entry-size whole lemon tart, without decorations. Other sizes are available on the bakery’s official menu.', whole:true, from:true },
  { id:'quiche', name:'Quiche lorraine', category:'Savory', description:'A savory slice of a French classic.', price:785, image:'https://images.unsplash.com/photo-1565181782289-457ee028de39?fm=jpg&q=80&w=1080&fit=max', badge:'SAVORY FAVORITE', detail:'One serving of Maison Odile’s quiche lorraine. Salad is not included.', whole:false }
];
export const money = cents => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
